// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6a__4mB_7yGu7ckVKfX93F1iaaRM_jk',
    appId: '1:875150817035:web:2f88e5be783f674571d40e',
    messagingSenderId: '875150817035',
    projectId: 'evaluacionprof',
    authDomain: 'evaluacionprof.firebaseapp.com',
    storageBucket: 'evaluacionprof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Sp2llg0SiK0ahOGhBoJjqGk9h0JLkvQ',
    appId: '1:875150817035:android:78a54fd172aa508671d40e',
    messagingSenderId: '875150817035',
    projectId: 'evaluacionprof',
    storageBucket: 'evaluacionprof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvJM7WIzvTqZP6FXmu3BFpzEbBPve1A4',
    appId: '1:875150817035:ios:1cb0c330b77f539771d40e',
    messagingSenderId: '875150817035',
    projectId: 'evaluacionprof',
    storageBucket: 'evaluacionprof.appspot.com',
    iosBundleId: 'com.example.evaluacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvJM7WIzvTqZP6FXmu3BFpzEbBPve1A4',
    appId: '1:875150817035:ios:1cb0c330b77f539771d40e',
    messagingSenderId: '875150817035',
    projectId: 'evaluacionprof',
    storageBucket: 'evaluacionprof.appspot.com',
    iosBundleId: 'com.example.evaluacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6a__4mB_7yGu7ckVKfX93F1iaaRM_jk',
    appId: '1:875150817035:web:2f88e5be783f674571d40e',
    messagingSenderId: '875150817035',
    projectId: 'evaluacionprof',
    authDomain: 'evaluacionprof.firebaseapp.com',
    storageBucket: 'evaluacionprof.appspot.com',
  );

}