// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhreG5FYlh7S4AZYiEuIrflpYuEIe4Y6A',
    appId: '1:246068591885:web:1f828b20acea1e2992c444',
    messagingSenderId: '246068591885',
    projectId: 'flutter-test-828ad',
    authDomain: 'flutter-test-828ad.firebaseapp.com',
    storageBucket: 'flutter-test-828ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQanuiQrVjk1JXldRAwQXps8vuY0I3z8',
    appId: '1:246068591885:android:b0d36d6ecab6034d92c444',
    messagingSenderId: '246068591885',
    projectId: 'flutter-test-828ad',
    storageBucket: 'flutter-test-828ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDls2KgwzYexezXEztepbsNzQYpOBJsHMw',
    appId: '1:246068591885:ios:f92537ebafea694392c444',
    messagingSenderId: '246068591885',
    projectId: 'flutter-test-828ad',
    storageBucket: 'flutter-test-828ad.appspot.com',
    iosBundleId: 'com.example.valoraProfesoresMedac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDls2KgwzYexezXEztepbsNzQYpOBJsHMw',
    appId: '1:246068591885:ios:f92537ebafea694392c444',
    messagingSenderId: '246068591885',
    projectId: 'flutter-test-828ad',
    storageBucket: 'flutter-test-828ad.appspot.com',
    iosBundleId: 'com.example.valoraProfesoresMedac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhreG5FYlh7S4AZYiEuIrflpYuEIe4Y6A',
    appId: '1:246068591885:web:5705ff2d0fde434e92c444',
    messagingSenderId: '246068591885',
    projectId: 'flutter-test-828ad',
    authDomain: 'flutter-test-828ad.firebaseapp.com',
    storageBucket: 'flutter-test-828ad.appspot.com',
  );

}